### ISSUE TITLE
Top buttons

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-project#1]
## User Story, Top buttons
As a user, I need buttons
for every preset city, 
so that I can select them/navigate between them

## Description (Scribble)

<img width="279" alt="Homepage" src="https://user-images.githubusercontent.com/111958591/197200700-dbc81404-a214-4250-8137-487a9c5c0ada.png">

<img width="290" alt="Buttons" src="https://user-images.githubusercontent.com/111958591/197731735-e09ff204-0911-4213-b32c-49b419d6e843.png">

## Acceptance criteria
- [x] if I click on a Button, it shows me the weather of that city

## Tasks
- [x] create a new React app
- [x] remove unnecessary data
- [x] create new JS file in components
- [x] add the buttons
- [x] add styling to the buttons

## Size
small

**Comment by VladF146** [comment]
A a user I neew buttons for every preset city, so that I can select them/navigate between them
