### ISSUE TITLE
Activities Page

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-project#14]
## Activities Page
As a User in need, a page
so that I can add and update my activities

## Description (Scribble)
<img width="506" alt="Page" src="https://user-images.githubusercontent.com/111958591/201376336-973de412-001c-42c8-ac5c-fb193c3f8cb4.png">

## Acceptance criteria
- [x] insert activity name
- [x] add date and time
- [x] insert City name
- [x] add button to add activities
- [x] delete button to delete the activities

## Tasks
- [x] add input field for activity and city name
- [x] add date and time input field
- [x] add button to delete and add cards
- [x] add a delete and add function

## Size
(medium)
