### ISSUE TITLE
Local storage hook

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-project#15]
As a User
I need the local storage
so that I save all my added cards

## Acceptance criteria
- [x] save items in local storage
- [x] get items from local storage

## Tasks
- [x] add a new folder for hooks
- [x] add useLocalStorage.js
- [x] write useLocalStorage function
- [x] insert in Card.js

## Size
(small)
