### ISSUE TITLE
User Story, search bar

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-project#3]
##
As a user
I need an input field and a search geolocation button
so that I can search for cities

## Description (Scribble)

<img width="375" alt="searchbar and button" src="https://user-images.githubusercontent.com/111958591/198047993-62028dd7-b2f6-4a11-a512-6df2f0090c21.png">

## Acceptance criteria
- [x] if I type text into the input field, I get a list of cities matching the text as I type
- [x] If I click the location button, I get the current Weather of the city I am (no function yet, just the button)

## Tasks
- [x] add an input search field
- [x] add a search button
- [x] add a location button

## Size
(small)
