### ISSUE TITLE
Actual Weather Card

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-project#5]
##
As a user
I need the actual weather, time and date
so that I know the actual temperature, time and date

## Description (Scribble)

<img width="418" alt="Location,Time and actual weather" src="https://user-images.githubusercontent.com/111958591/198565007-b49d33cf-8704-4950-9d59-c2da5992a3cc.png">

## Tasks
- [x] add the Local Time 
- [x] add the current date
- [x] add current weather
- [x] add the sunrise
- [x] add the sunset 
- [x] add today's high temperature
- [x] add today's low temperature

## Size
(medium)

**Comment by dorosiemers** [comment]
I think you forgot to include the Acceptance Criteria.
