### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by BektasTu** [BektasTu/capstone-project#8]
## Navigation Bar
As a user
I need Navigation Bar
so that I can navigate through the pages

## Description (Scribble)

<img width="544" alt="NavBar" src="https://user-images.githubusercontent.com/111958591/199707722-1423481e-cc75-4857-ac16-14292e3cf5c3.png">

## Acceptance criteria
- [x]  the App should have a Header
- [x]  the App should have a Navbar and three pages
- [x] Navbar should be styled

## Tasks
- [x] add the Navbar
- [x] create links to each Page
- [x] style the created components

## Size
(small)
